export type CustomerMotorbike = {
    Address: string | null,
    AliasName: string | null,
    CardCode: string | null,
    CardName: string | null,
    Cellular: string | null,
    Dscription: string | null,
    City: string | null,
    Color: string | null,
    Country: string | null,
    DocEntry: number,
    Description: string,
    E_Mail: string | null,
    FolNumFrom: number,
    IntrSerial: string | null,
    ItemCode: string,
    LicTradNum: string,
    PTICode: string | null,
    Provincia: string | null,
    U_Chasis: string | null,
    U_Division: string | null,
    U_Marca: string | null,
    U_Modelo: string | null,
    U_Motor: string | null,
    U_Rubro: string,
    U_Subrubros: string,
    ValidTarjEq: string | null,
    ZipCode: string | null,
    id__: number
}